# Machine Learning Zoomcamp


## 1.8 Linear algebra refresher

- Vector operations
- Multiplication
  - Vector - vector multiplication
  - Matrix - vector multiplication
  - Matrix - matrix multiplication
- Identity matrix
- Inverse

In [1]:
import numpy as np

## 1) Vector operations

In [2]:
u = np.array([2, 4, 5, 6])

In [3]:
2 * u

array([ 4,  8, 10, 12])

In [4]:
v = np.array([1, 0, 0, 2])

In [5]:
u + v

array([3, 4, 5, 8])

In [6]:
u * v

array([ 2,  0,  0, 12])

## 2) Multiplication

In [7]:
v.shape[0]

4

In [9]:
u

array([2, 4, 5, 6])

In [10]:
v

array([1, 0, 0, 2])

### 2.1 Vector - vector multiplication

In [8]:
def vector_vector_multiplication(u, v):
  # make sure the vector have the same size
  assert u.shape[0] == v.shape[0]
  
  # n = the number of the element
  n = u.shape[0]

  result = 0.0

  # loop
  for i in range(n):
    result = result + u[i] * v[i]

  
  return result

In [11]:
vector_vector_multiplication(u, v)

14.0

In [12]:
u.dot(v)

14

### 2.2 Matrix - vector multiplication

In [13]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [36]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [14]:
U.shape

(3, 4)

In [15]:
def matrix_vector_multiplication(U, v):
  # make sure the vector have the same size (number of column u = number of row of V)
  assert U.shape[1] == v.shape[0]

  # n = the number of the column of u
  num_rows = U.shape[0]

  result = np.zeros(num_rows)

  # loop
  for i in range(num_rows):
    result[i] = vector_vector_multiplication(U[i], v)
  
  return result

In [16]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [17]:
U.dot(v)

array([14,  5,  5])

### Matrix - matrix multiplication

In [23]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0]
])

In [26]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [27]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [28]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## 3) Identity Matrix

In [29]:
I = np.eye(3)

In [30]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [32]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## 4) Inverse

In [33]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [34]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [35]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])